trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: FirstJob
        steps:
          - bash: echo FirstJob Build !
          - bash: echo var $(PipeLineLevelVariable)
          - bash: echo var $(Build.BuildId)
          - bash: echo var $(Build.BuildNumber)
          - bash: echo var $(Build.SourceBranchName)
          - bash: echo var $(Build.SourcesDirectory)
          - bash: ls -R  $(System.DefaultWorkingDirectory)
          - bash: echo var $(Build.ArtifactStagingDirectory)
          - bash: java -version
          - bash: python --version
          - bash: mvn -version
          - bash: node --version
          - bash: ls -R $(Build.ArtifactStagingDirectory)
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: |
                **/*.yaml
                **/*.tf
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - bash: ls -R $(Build.ArtifactStagingDirectory)
          
  # - job: SecondJob
  #   steps:
  #     - bash: echo SecondJob Build !       
  # - stage: DevDeploy
  #   variables: 
  #    environment : dev
  #   dependsOn: Build
  #   jobs:
  #     - job: FirstJob
  #       steps:
  #         - bash: echo FirstJob $(environment)Deploy Build ! 

  # - stage: QaDeploy
  #   variables: 
  #    environment : qa  
  #   dependsOn: Build
  #   jobs:
  #     - job: FirstJob
  #       steps:
  #         - bash: echo FirstJob $(environment)Deploy Build !   
  # - stage: ProdDeploy
  #   dependsOn:
  #   - DevDeploy
  #   - QaDeploy
  #   jobs:
  #     - job: FirstJob
  #       steps:
  #         - bash: echo FirstJob ProdDeploy Build !   
