trigger:
- master
# strategy:
#  matrix:
#   linux:
#     operatingSystem: 'ubuntu-latest'
#   mac:
#    operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - bash: echo "Start dev build"

  - stage: DevDeploy
    jobs:
      - deployment: DevDeployJob
        environment: Dev
        strategy:
         runOnce:
            deploy:
               steps:
                 - script : echo deploy to dev
  - stage: qaDeploy
    jobs:
      - deployment: QaDeployJob
        environment: QA
        strategy:
         runOnce:
            deploy:
               steps:
                 - script : echo deploy to QA                  
    

